import type { OrderTabs } from './types';

export const ORDER_TAB_MAP: Record<OrderTabs, string[]> = {
  LIMIT: [
    'Limit',
    '限价委托',
    '限價委託',
    'Limite',
    'Лимит',
    'ลิมิต',
    'Giới hạn',
    'Batas',
    'Limit',
    'Limit',
    'Limite',
    'Z limitem',
    'Limit',
    'Limită',
    'Ліміт',
  ],
  MARKET: [
    'Market',
    '市价委托',
    '市價委託',
    'Marché',
    'Маркет',
    'มาร์เก็ต',
    'Thị trường',
    'Pasar',
    'Piyasa',
    'Markt',
    'Mercato',
    'Rynek',
    'Trh',
    'Piață',
    'Маркет',
  ],
  STOP: [
    'Stop',
    '止盈止损',
    '止盈止損',
    'Stop',
    'Стоп',
    'สต๊อป',
    'Dừng',
    'Penghentian',
    'Durdur',
    'Stop',
    'Stop-loss',
    'Stop',
    'Stop',
    'Stop',
    'Стоп',
  ],
  TRAILING_STOP: [
    'Trailing stop',
    '移动止盈止损',
    '移動止盈止損',
    'Trailing stop',
    'Остановка трейлинга',
    'เทรลลิ่งสต๊อป',
    'Trailing stop',
    'Trailing stop (Stop trailing)',
    'Takip eden stop',
    'Trailing stop',
    'Trailing stop',
    'Trailing stop',
    'Trailing stop',
    'Stop trailing',
    'Трейлінг-стоп',
  ],
  ADVANCED_LIMIT: [
    'Advanced limit',
    '高级限价委托',
    '高級限價委託',
    'Limite avancée',
    'Расширенный лимит',
    'ลิมิตขั้นสูง',
    'Giới hạn nâng cao',
    'Advanced limit',
    'Gelişmiş limit',
    'Erweitertes Limit',
    'Limite avanzato',
    'Limit zaawansowany',
    'Pokročilý limit order',
    'Limită avansată',
    'Розширений ліміт',
  ],
};
