export const LIMIT_TAB_TEXTS = [
  'Limit',
  '限价委托',
  '限價委託',
  'Limite',
  'Лимит',
  'ลิมิต',
  'Giới hạn',
  'Batas',
  'Limit',
  'Limit',
  'Limite',
  'Z limitem',
  'Limit',
  'Limită',
  'Ліміт',
];

export const MARKET_TAB_TEXTS = [
  'Market',
  '市价委托',
  '市價委託',
  'Marché',
  'Маркет',
  'มาร์เก็ต',
  'Thị trường',
  'Pasar',
  'Piyasa',
  'Markt',
  'Mercato',
  'Rynek',
  'Trh',
  'Piață',
  'Маркет',
];

export const ADVANCED_LIMIT_TEXTS = [
  'Advanced limit',
  '高级限价委托',
  '高級限價委託',
  'Limite avancée',
  'Расширенный лимит',
  'ลิมิตขั้นสูง',
  'Giới hạn nâng cao',
  'Advanced limit',
  'Gelişmiş limit',
  'Erweitertes Limit',
  'Limite avanzato',
  'Limit zaawansowany',
  'Pokročilý limit order',
  'Limită avansată',
  'Розширений ліміт',
];
